# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.srcs/sources_1/bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
# IP: The module: 'system_axi_mem_intercon_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/bd_5cbf.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_1/bd_5cbf_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_2/bd_5cbf_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_3/bd_5cbf_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_4/bd_5cbf_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_5/bd_5cbf_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_6/bd_5cbf_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_7/bd_5cbf_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_8/bd_5cbf_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_9/bd_5cbf_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_1/bd_5cbf_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_5/bd_5cbf_s00a2s_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_6/bd_5cbf_sarn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_7/bd_5cbf_srn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_8/bd_5cbf_m00s2a_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_mem_intercon_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_mem_intercon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.srcs/sources_1/bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
# IP: The module: 'system_axi_mem_intercon_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/bd_5cbf.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_1/bd_5cbf_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_2/bd_5cbf_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_3/bd_5cbf_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_4/bd_5cbf_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_5/bd_5cbf_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_6/bd_5cbf_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_7/bd_5cbf_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_8/bd_5cbf_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_9/bd_5cbf_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_1/bd_5cbf_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_5/bd_5cbf_s00a2s_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_6/bd_5cbf_sarn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_7/bd_5cbf_srn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/bd_0/ip/ip_8/bd_5cbf_m00s2a_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_mem_intercon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_axi_mem_intercon_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_mem_intercon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
