# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.srcs/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
# IP: The module: 'system_ps7_0_axi_periph_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/bd_7aa6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_1/bd_7aa6_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_2/bd_7aa6_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_3/bd_7aa6_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_4/bd_7aa6_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_5/bd_7aa6_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_6/bd_7aa6_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_7/bd_7aa6_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_8/bd_7aa6_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_9/bd_7aa6_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_10/bd_7aa6_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_11/bd_7aa6_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_12/bd_7aa6_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_13/bd_7aa6_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_14/bd_7aa6_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_15/bd_7aa6_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_16/bd_7aa6_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_17/bd_7aa6_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_18/bd_7aa6_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_19/bd_7aa6_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_20/bd_7aa6_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_21/bd_7aa6_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_22/bd_7aa6_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_23/bd_7aa6_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_24/bd_7aa6_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_25/bd_7aa6_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_26/bd_7aa6_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_27/bd_7aa6_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_28/bd_7aa6_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_29/bd_7aa6_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_30/bd_7aa6_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_31/bd_7aa6_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_32/bd_7aa6_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_33/bd_7aa6_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_34/bd_7aa6_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_35/bd_7aa6_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_36/bd_7aa6_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_37/bd_7aa6_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_38/bd_7aa6_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_39/bd_7aa6_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_1/bd_7aa6_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_2/bd_7aa6_arinsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_3/bd_7aa6_rinsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_4/bd_7aa6_awinsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_5/bd_7aa6_winsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_6/bd_7aa6_binsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_7/bd_7aa6_aroutsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_8/bd_7aa6_routsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_9/bd_7aa6_awoutsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_10/bd_7aa6_woutsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_11/bd_7aa6_boutsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_12/bd_7aa6_arni_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_13/bd_7aa6_rni_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_14/bd_7aa6_awni_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_15/bd_7aa6_wni_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_16/bd_7aa6_bni_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_20/bd_7aa6_s00a2s_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_21/bd_7aa6_sarn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_22/bd_7aa6_srn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_23/bd_7aa6_sawn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_24/bd_7aa6_swn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_25/bd_7aa6_sbn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_26/bd_7aa6_m00s2a_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_27/bd_7aa6_m00arn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_28/bd_7aa6_m00rn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_29/bd_7aa6_m00awn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_30/bd_7aa6_m00wn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_31/bd_7aa6_m00bn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_33/bd_7aa6_m01s2a_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_34/bd_7aa6_m01arn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_35/bd_7aa6_m01rn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_36/bd_7aa6_m01awn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_37/bd_7aa6_m01wn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_38/bd_7aa6_m01bn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ps7_0_axi_periph_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ps7_0_axi_periph_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.srcs/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
# IP: The module: 'system_ps7_0_axi_periph_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/bd_7aa6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_1/bd_7aa6_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_2/bd_7aa6_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_3/bd_7aa6_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_4/bd_7aa6_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_5/bd_7aa6_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_6/bd_7aa6_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_7/bd_7aa6_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_8/bd_7aa6_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_9/bd_7aa6_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_10/bd_7aa6_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_11/bd_7aa6_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_12/bd_7aa6_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_13/bd_7aa6_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_14/bd_7aa6_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_15/bd_7aa6_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_16/bd_7aa6_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_17/bd_7aa6_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_18/bd_7aa6_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_19/bd_7aa6_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_20/bd_7aa6_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_21/bd_7aa6_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_22/bd_7aa6_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_23/bd_7aa6_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_24/bd_7aa6_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_25/bd_7aa6_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_26/bd_7aa6_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_27/bd_7aa6_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_28/bd_7aa6_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_29/bd_7aa6_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_30/bd_7aa6_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_31/bd_7aa6_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_32/bd_7aa6_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_33/bd_7aa6_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_34/bd_7aa6_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_35/bd_7aa6_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_36/bd_7aa6_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_37/bd_7aa6_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_38/bd_7aa6_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_39/bd_7aa6_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_1/bd_7aa6_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_2/bd_7aa6_arinsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_3/bd_7aa6_rinsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_4/bd_7aa6_awinsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_5/bd_7aa6_winsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_6/bd_7aa6_binsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_7/bd_7aa6_aroutsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_8/bd_7aa6_routsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_9/bd_7aa6_awoutsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_10/bd_7aa6_woutsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_11/bd_7aa6_boutsw_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_12/bd_7aa6_arni_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_13/bd_7aa6_rni_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_14/bd_7aa6_awni_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_15/bd_7aa6_wni_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_16/bd_7aa6_bni_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_20/bd_7aa6_s00a2s_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_21/bd_7aa6_sarn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_22/bd_7aa6_srn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_23/bd_7aa6_sawn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_24/bd_7aa6_swn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_25/bd_7aa6_sbn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_26/bd_7aa6_m00s2a_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_27/bd_7aa6_m00arn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_28/bd_7aa6_m00rn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_29/bd_7aa6_m00awn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_30/bd_7aa6_m00wn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_31/bd_7aa6_m00bn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_33/bd_7aa6_m01s2a_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_34/bd_7aa6_m01arn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_35/bd_7aa6_m01rn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_36/bd_7aa6_m01awn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_37/bd_7aa6_m01wn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/bd_0/ip/ip_38/bd_7aa6_m01bn_0_ooc.xdc

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ps7_0_axi_periph_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/user/Documents/AAD/space_invaders/vivado/vivado_proj_hdmi/zybo_hdmi.gen/sources_1/bd/system/ip/system_ps7_0_axi_periph_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ps7_0_axi_periph_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
